import numpy as np
import matplotlib.pyplot as plt

# Line to unpack .xvg generated by GROMACS
x,y = np.loadtxt("./nvte-temperature.xvg",comments=["@","#"],unpack=True)

# As the energy is just too high in the start, one has to start at the

plt.figure(dpi=200)
plt.plot(x,y, label="temperature")
plt.plot(x, np.ones(len(x))*300, label="expected")
plt.xlabel("time (ps)")
plt.ylabel("kelvin")
plt.title("Evolution of Temperature - GROMACS")
plt.legend()
plt.show()