import numpy as np
import matplotlib.pyplot as plt

# Line to unpack .xvg generated by GROMACS
x,y = np.loadtxt("./npt-pressure.xvg",comments=["@","#"],unpack=True)

# As the energy is just too high in the start, one has to start at the

plt.figure(dpi=200)
plt.plot(x,y, label="pressure")
plt.plot(x, np.ones(len(x)), label="expected")
plt.xlabel("time (ns)")
plt.ylabel("bar")
plt.title("Evolution of Pressure - GROMACS")
plt.legend()
plt.show()